[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Swarup"
authors = [{name = "Swarup Tripathy", email = "mstrider10@gmail.com"}]
dynamic = ["version", "description"]
